[package]
name = "virtio-blk"
version = "0.0.1"
authors = ["Seiya Nuta <nuta@seiya.me>"]

[dependencies]
resea = { path = "../../libs/resea" }
resea_langitems = { path = "../../libs/resea/langitems" }
virtio = { path = "../../libs/virtio" }
