name: fs
id: 8
category: interface
license: Public Domain
summary: The interface of fs
description:

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
requires: []
lib_requires: []

# interfaces which this package uses
uses: []

# interfaces which this package implements
implements: [pager]


#
#  Type definitions
#
types:
  filemode:
    type: const
    size: uint32
    consts:
      FILEMODE_READ:   0x0001
      FILEMODE_WRITE:  0x0004
      FILEMODE_APPEND: 0x0008


#
#  interface definitions
#
interface:
  open:
    id: 1
    payloads:
      - name: path
        type: Array<uchar>
        attrs: [readonly]
      - name: mode
        type: fs(filemode)
  open_reply:
    id: 2
    payloads:
      - name: result
        type: result
      - name: file
        type: id

  close:
    id: 3
    payloads:
      - name: file
        type: id
  close_reply:
    id: 4
    payloads:
      - name: result
        type: result

  read:
    id: 5
    payloads:
      - name: file
        type: id
      - name: offset
        type: offset
  read_reply:
    id: 6
    payloads:
      - name: result
        type: result
      - name: data
        type: data

  write:
    id: 7
    payloads:
      - name: file
        type: id
      - name: offset
        type: offset
      - name: data
        type: data
        attrs: [readonly]
  write_reply:
    id: 8
    payloads:
      - name: result
        type: result
