language: node_js

linux_addons: &linux_addons
  apt:
    packages:
      - "git"
      - "wget"
      - "make"
      - "flex"
      - "bison"
      - "gperf"
      - "python"
      - "libncurses-dev"
      - "python-serial"

matrix:
  include:
    - os: linux
      node_js: "10"
      addons: *linux_addons
    - os: linux
      node_js: "8"
      addons: *linux_addons
    - os: osx
      osx_image: xcode9.3
      node_js: "10"

install:
  - yarn
script:
  - yarn build
  - yarn coverage
after_script:
  - yarn global add codeclimate-test-reporter
  - if [[ $TRAVIS_OS_NAME = "osx" ]] then yarn nyc report --reporter=text-lcov | codeclimate-test-reporter; fi
cache:
  yarn: true
  directories:
    - esp32/deps

notifications:
  on_success: change
  on_failure: change
