os: linux
dist: trusty
sudo: false

matrix:
  include:
    - language: ruby
      env: M=server
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      install:
        - cd server
        - bundle install --jobs 2 --path vendor/bundle
        - bundle exec rails db:migrate RAILS_ENV=test
      script: bundle exec rspec

    - language: node_js
      node_js: "8"
      env: M=ui
      cache: yarn
      install:
        - cd server
        - yarn
      script: npm run build

    - language: c
      env: M=linux:x86_64
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - build-essential
            - wget
            - qemu
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install: npm install -g yarn
      script:
        - cd linux
        - ./builder --test x86_64


    - language: c
      env: M=linux:raspberrypi
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - build-essential
            - wget
            - qemu
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install: npm install -g yarn
      script:
        - cd linux
        - ./builder --test raspberrypi

notifications:
  on_success: change
  on_failure: change