language: rust
rust: nightly
dist: trusty
sudo: false

cache:
  pip: true

notifications:
  on_success: change
  on_failure: change

kernel_addons: &kernel_addons
    apt:
      sources:
        - llvm-toolchain-trusty-6.0
        - ubuntu-toolchain-r-test
      packages:
        - clang-6.0
        - lld-6.0
        - qemu-system-x86
        - mtools

matrix:
  include:
    - env: M=kernel ARCH=x64
      addons: *kernel_addons
    - env: M=lib LIB=netstack

before_script:
  - ./tools/bootstrap

script:
  - ./tools/ci.py
