os: linux
dist: trusty
sudo: false

env: M=dummy

matrix:
  include:
    - language: node_js
      node_js: "8"
      env: M=linux:x86_64
      sudo: true # because of mknod
      addons:
        apt:
          packages:
            - build-essential
            - wget
            - qemu
            - zsh
            - nodejs
            - virtualbox
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install:
        - npm install -g yarn node-gyp
        - cd linux
      script:
        - make TARGET=x86_64

    - language: node_js
      node_js: "8"
      env: M=linux:raspberrypi3
      sudo: true # because of mknod
      addons:
        apt:
          packages:
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - g++-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - build-essential
            - wget
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
          - qemu
      install:
        - npm install -g yarn node-gyp
        - mkdir -p qemu
        - cd qemu
        - wget https://download.qemu.org/qemu-2.10.1.tar.xz
        - tar xf qemu-2.10.1.tar.xz
        - cd qemu-2.10.1
        - ./configure --target-list=arm-softmmu
        - make -j2
        - sudo make install
        - cd ../../linux
      script:
        - make TARGET=raspberrypi3

    - language: ruby
      env: M=server:backend:sqlite3
      services:
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      install:
        - cd server
        - bundle install --jobs 2 --path vendor/bundle
        - 'printf "test:\n  adapter: sqlite3\n  database: db/test.sqlite3" > config/database.yml'
        - bundle exec rails db:migrate RAILS_ENV=test
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rspec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - language: ruby
      env: M=server:backend:postgresql
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      install:
        - cd server
        - psql -c 'create database travis_ci_test;' -U postgres
        - 'printf "test:\n  adapter: postgresql\n  database: travis_ci_test" > config/database.yml'
        - bundle install --jobs 2 --path vendor/bundle
        - bundle exec rails db:migrate RAILS_ENV=test
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rspec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - language: node_js
      node_js: "8"
      env: M=server:frontend
      cache: yarn
      install:
        - cd server/ui
        - cp config.js.example config.js
        - yarn
      script: npm run build

    - language: node_js
      env: M=installer:macos
      os: osx
      osx_image: xcode9.1
      node_js: "8"
      cache:
        directories:
          - installer/node_modules
          - "$HOME/.electron"
          - "$HOME/.cache"
      install:
        - cd installer
        - npm install -g yarn
        - yarn
      script:
        - yarn run build:macos

    - language: node_js
      node_js: "8"
      env: M=installer:linux
      cache:
        directories:
          - installer/node_modules
      install:
        - cd installer
        - yarn
      script:
        - yarn run build:linux

    - language: node_js
      node_js: "8"
      env: M=client
      cache:
        directories:
          - client/node_modules
      install:
        - cd client
        - yarn
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn run cov
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  on_success: change
  on_failure: change
