language: node_js

matrix:
  include:
    - os: linux
      node_js: "10"
    - os: linux
      node_js: "8"
    - os: osx
      osx_image: xcode9.3
      node_js: "10"

install: yarn
script:
  - yarn build
  - yarn test
after_script:
  - yarn global add codeclimate-test-reporter
  - yarn nyc report --reporter=text-lcov | codeclimate-test-reporter
cache:
  yarn: true

notifications:
  on_success: change
  on_failure: change
