language: ruby
services:
  - postgresql
  - mysql

rvm:
  - 2.3.1
  - 2.2.5

cache:
  directories:
    - vendor/bundle

env:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql

# http://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database
before_install:
  - mysql -u root -e 'set global innodb_file_format = Barracuda'
  - mysql -u root -e 'set global innodb_large_prefix = 1'
  - sudo service mysql restart
  - '[ "$DB" = "mysql" ] && git apply travis/support-utf8mb4-in-mysql.patch'

install:
  - cp travis/database.yml config/database.yml
  - mysql -e 'create database busybook_test'
  - mysql -e 'ALTER DATABASE busybook_test CHARACTER SET utf8mb4 COLLATE utf8mb4_bin'
  - psql -c 'create database busybook_test' -U postgres
  - bundle install --jobs 4 --path vendor/bundle
  - bundle exec rake db:migrate
  - bundle exec rake user:add username=guest password=123

script:
  - ./travis/script.sh
