language: node_js

linux_addons: &linux_addons
  apt:


jobs:
  include:
    - stage: test
      os: linux
      node_js: "10"
      install:
        - yarn
      script:
        - yarn build
        - yarn coverage
      addons:
        apt:
          packages:
            - "git"
            - "wget"
            - "make"
            - "flex"
            - "bison"
            - "gperf"
            - "python"
            - "libncurses-dev"
            - "python-serial"

    - os: osx
      osx_image: xcode9.3
      node_js: "10"
      install:
        - yarn
      script:
        - yarn build
        - yarn coverage
      after_script:
        - yarn global add codeclimate-test-reporter
        - yarn nyc report --reporter=text-lcov | codeclimate-test-reporter

    - stage: release
      script: skip
      deploy:
        provider: npm
        email: nuta@seiya.me
        api_key: "$NPM_API_KEY"
        skip_cleanup: true
        on:
          tags: true

cache:
  yarn: true
  directories:
    - esp32/deps

notifications:
  on_success: change
  on_failure: change
