language: rust
dist: trusty
sudo: false

notifications:
  on_success: change
  on_failure: change

x64_kernel: &x64_kernel
  env: M=kernel ARCH=x64
  addons:
    apt:
      sources:
        - llvm-toolchain-trusty-6.0
        - ubuntu-toolchain-r-test
      packages:
        - clang-6.0
        - lld-6.0
        - qemu-system-x86
        - mtools
  before_script:
    - ./tools/bootstrap
  script:
    - make -j2 build ARCH=x64 ANTLR4="java -jar $PWD/antlr-4.7.1-complete.jar" SERVERS="test" CC=clang-6.0 LD=ld.lld-6.0

posix_kernel: &posix_kernel
  env: M=kernel ARCH=posix
  before_script:
    - ./tools/bootstrap
  script:
    - make -j2 ARCH=posix ANTLR4="java -jar $PWD/antlr-4.7.1-complete.jar" run

matrix:
  include:
    - *x64_kernel
    - *posix_kernel

cache:
  pip: true
