os: linux
dist: trusty
sudo: false

matrix:
  include:
    - language: ruby
      env: M=server
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      install:
        - cd server
        - bundle install --jobs 2 --path vendor/bundle
        - bundle exec rails db:migrate RAILS_ENV=test
      script: bundle exec rspec

    - language: node_js
      node_js: "8"
      env: M=ui
      cache: yarn
      install:
        - cd server
        - yarn
      script: npm run build

    - language: c
      env: M=linux:x86_64
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - build-essential
            - wget
            - qemu
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install: npm install -g yarn
      script:
        - cd linux
        - ./builder --test x86_64


    - language: c
      env: M=linux:raspberrypi
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - build-essential
            - wget
            - qemu
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install: npm install -g yarn
      script:
        - cd linux
        - ./builder --test raspberrypi

    - language: node_js
      env: M=installer:macos
      os: osx
      osx_image: xcode8.3
      node_js: "8"
      cache:
        directories:
          - installer/node_modules
          - "$HOME/.electron"
          - "$HOME/.cache"
      install:
        - cd installer
        - npm install -g yarn
        - yarn
      script:
        - yarn run test

    - language: node_js
      node_js: "8"
      env: M=installer:linux
      addons:
        apt:
          packages:
            - xvfb
      cache:
        directories:
          - installer/node_modules
          - "$HOME/.electron"
          - "$HOME/.cache"
      install:
        - cd installer
        - yarn
      before_script:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      script:
        - yarn run test

    - language: node_js
      env: M=dependencies
      node_js: "8"
      install:
        - gem install --no-ri --no-rdoc hakiri
        - npm install -g nsp
      script:
        - ./tools/check-dependencies.py

  allow_failures:
    - language: node_js
      env: M=coding-styles
      node_js: "8"
      install:
        -  npm i -g eslint eslint-config-standard eslint-plugin-standard   eslint-plugin-import eslint-plugin-node eslint-plugin-promise
      script:
        - ./tools/check-coding-styles.py
  
notifications:
  on_success: change
  on_failure: change