os: linux
dist: trusty
sudo: false

env: M=dummy

matrix:
  include:
    - language: c
      env: M=linux:x86_64
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - build-essential
            - wget
            - qemu
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install: npm install -g yarn
      script:
        - cd linux
        - ./builder --test x86_64

    - language: c
      env: M=linux:raspberrypi3
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - g++-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - build-essential
            - wget
            - zsh
            - nodejs
      cache:
        apt: true
        directories:
          - linux/build/downloads
      install:
        - npm install -g yarn
        - mkdir -p linux/build/downloads
        - cd linux/build/downloads
        - wget https://download.qemu.org/qemu-2.10.1.tar.xz
        - tar xf qemu-2.10.1.tar.xz
        - cd qemu-2.10.1
        - ./configure
        - make -j2
        - sudo make install
        - cd ../../..
      script:
        - ./builder raspberrypi3
        
    - language: ruby
      env: M=server:backend
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      install:
        - cd server
        - bundle install --jobs 2 --path vendor/bundle
        - bundle exec rails db:migrate RAILS_ENV=test
      script: bundle exec rspec

    - language: node_js
      node_js: "8"
      env: M=server:frontend
      cache: yarn
      install:
        - cd server
        - yarn
      script: npm run build

    - language: node_js
      env: M=installer:macos
      os: osx
      osx_image: xcode9.1
      node_js: "8"
      cache:
        directories:
          - installer/node_modules
          - "$HOME/.electron"
          - "$HOME/.cache"
      install:
        - cd installer
        - npm install -g yarn
        - yarn
      script:
        - yarn run build:macos

    - language: node_js
      node_js: "8"
      env: M=installer:linux
      cache:
        directories:
          - installer/node_modules
      install:
        - cd installer
        - yarn
      script:
        - yarn run build:linux

    - language: node_js
      env: M=dependencies
      node_js: "8"
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6
      cache:
        apt: true
      install:
        - gem install --no-ri --no-rdoc hakiri
        - npm install -g nsp
      script:
        - python3.6 ./tools/check-dependencies.py

    - language: node_js
      env: M=coding-styles
      node_js: "8"
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.6
      cache:
        apt: true
      install:
        -  npm i -g eslint eslint-config-standard eslint-plugin-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise
      script:
        - python3.6 ./tools/check-coding-styles.py

  allow_failures:
    - env: M=coding-styles
 
notifications:
  on_success: change
  on_failure: change