os: linux
dist: trusty
sudo: false

env:
  global:
    - secure: "NGI9TLs1QtrzbUN2WOQz7Xl4+d7M3ahEjJ4xl1lJIogHXugZFrgNwL6PW+ROYwDpg1NAdX5B7qinwQuqXs/wL6FFJ+pGNZqWB7g2CqmZ2/OhnXKpm08De7DmAmIoGI0vCOMvx5//8sPnGJFJDQJduY9VYZMJjCVGJGndxl81tNBsipXSvZzV7jREFz3VdKvrf1L6xRJfpMEVr4aIN821J9Vj/mY+iJsTB+w0CZ++Z2S1WwLuzUxkJvhKvbzYPqeFg2ontPMhP9beD6oUV/8Hqp4Ip9Vem1bfvtXHSyzqlp00kcXDukfVHLaF77Vcb1WX6XgBvcg0hqsh45xlSWdjYoGK/EGCrm0m5hXWAmLTf22tCtKW0CGk2O9onQv9qzU3HjBpQYdgbZAY8Ho6EZdXu+fwvU9K+3A5E5Kx6l/055XebWZYGItuS03s1hWyTHpDurxLg4MBpgBJjq3J3l0llc3BZBJB6ePvVmRhq1IB7Ns6/SDN9S3BCA6UDT2FdDp/skBV2kX3ACHC8F87BimQwH8gBgwzQfJB8IJOqBo9/+FmA5T7JdM12uCIbHxaUOiYxvDCM6UV5yarVh+BWmS3fUi6yZ8xAtI0hTrVug2YEuRjzZFPn00GWFr7DtWMnJTSi9bMjRv/sn//WBGO+Ata1p2BwpqBDG6wYaaPe8Hms9A="
    - secure: "ppxV2HgHH9R5908CdysWowzU28UgC4QAnA5s+tk5IomHCCJBzBnEEFQ+tjQrAk35E/CRjG0gkCP6jYnQVixU4vx37j4ce7tBfJI4IpQC1/58FP7A89iauAKLB7mtpjSvfMEjErurSPO2/uZ2wL5GUwodbowqlO1DeEw5xlGbLizIwa778zv6qq1baJFg9U/ze44BYaQak88iKinH8j6tfJjKgbqWx2gMkk7/xupyQXRPtgftJMwiRYQfanKQUIbjafI9QJExvqNXt9OSjHqjUSYVfQMt4i4lKc7PKFP0ejQedX9hTecVGNH6ZYcGyUZT4F0MBuwDQtL66CfqIp+IBCIFHSK5siuj1HFFt7f6zeOdYzyHdNQRepD6ikz1PWHFEMKFFS99yFqdqvA3YlDDnYK9cmw6lMf2CDzGdl1E9aBoS5i81NPU56dzTmxSS5+C0AgctUwzFKxcbdoTlxzDRcIYjLhb+6tiLXjPvaXk/0mSiecmCIr2Q67EsfHB3cuigTvsMAI7TjBKxYoUOtRvFwat+fYQxBvDSRukGR4zlBIALYk6Fz6ecaN95I7Q98nOaV0i4Ltv1i4I2Jw0xGQZGW9V4d8IPOLPmkoYELEEQOJN/o1WX67YjkF0dYlwqzNB/OuKcmNShJTFnbGNUomYpYiqtDv6CNQhsyC8Q3/OKqQ="

matrix:
  include:
    - language: node_js
      node_js: "8"
      sudo: true # because of losetup(8)
      env: M=linux:raspberrypi3
      addons:
        apt:
          packages:
            - binutils-arm-linux-gnueabihf
            - gcc-arm-linux-gnueabihf
            - g++-arm-linux-gnueabihf
            - libc6-dev-armhf-cross
            - build-essential
            - wget
            - zsh
            - realpath
            - nodejs
      cache:
        apt: true
        yarn: true
        directories:
          - linux/build/downloads
      install:
        - npm install -g yarn
        - cd linux/pkgbuilder
        - yarn
        - cd ..
      script:
        - BUILD=release make TARGET=raspberrypi3

    - language: ruby
      rvm: 2.5
      env: M=server:backend:sqlite3
      services:
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      # See https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
      before_install:
        - gem update --system --no-doc
      install:
        - cd server
        - bundle install --jobs 2 --path vendor/bundle
        - 'printf "test:\n  adapter: sqlite3\n  database: db/test.sqlite3" > config/database.yml'
        - bundle exec rails db:migrate RAILS_ENV=test
      script:
        - bundle exec rspec

    - language: ruby
      rvm: 2.5
      env: M=server:backend:postgresql
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      # See https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
      before_install:
        - gem update --system --no-doc
      install:
        - cd server
        - psql -c 'create database travis_ci_test;' -U postgres
        - 'printf "test:\n  adapter: postgresql\n  database: travis_ci_test" > config/database.yml'
        - bundle install --jobs 2 --path vendor/bundle
        - bundle exec rails db:migrate RAILS_ENV=test
      script:
        - bundle exec rspec

    - language: node_js
      node_js: "8"
      env: M=server:frontend
      cache: yarn
      install:
        - cd ui
        - yarn
      script: npm run build

    - language: node_js
      env:
        - M=desktop:macos
      os: osx
      osx_image: xcode9.1
      node_js: "8"
      cache:
        yarn: true
        directories:
          - "$HOME/.electron"
          - "$HOME/.cache"
      install:
        - npm install -g yarn
        - cd ui && yarn && cd ..
        - cd desktop
        - yarn
      script:
        - yarn run build:macos
      before_deploy:
        - zip -r app/MakeStack-darwin-x64/MakeStack-macos-$TRAVIS_TAG.app.zip app/MakeStack-darwin-x64/MakeStack.app
      deploy:
        provider: releases
        api_key: "$GITHUB_API_KEY"
        file: app/MakeStack-darwin-x64/MakeStack-macos-$TRAVIS_TAG.app.zip
        skip_cleanup: true
        on:
          tags: true

    - language: node_js
      node_js: "8"
      env: M=desktop:linux
      cache:
        yarn: true
        directories:
          - "$HOME/.electron"
          - "$HOME/.cache"
      install:
        - cd ui && yarn && cd ..
        - cd desktop
        - yarn
      script:
        - yarn run build:linux

    - language: node_js
      node_js: "8"
      env: M=SDK
      cache:
        yarn: true
      install:
        - cd sdk
        - yarn
        - ../tools/relink-local-packages
      script:
        - yarn run coverage
      deploy:
        provider: npm
        email: nuta@seiya.me
        api_key: "$NPM_API_KEY"
        skip_cleanup: true
        on:
          tags: true

    - language: node_js
      node_js: "8"
      env: M=supervisor
      cache:
        yarn: true
      install:
        - cd supervisor
        - yarn
        - ../tools/relink-local-packages
      script:
        - yarn run coverage

    - language: node_js
      node_js: "8"
      env: M=runtime
      cache:
        yarn: true
      install:
        - cd runtime
        - yarn
      script:
        - yarn run coverage

    - language: node_js
      node_js: "8"
      env: M=makestack.org
      cache:
        yarn: true
      before_install:
        - >
          if [[ "${TRAVIS_BRANCH}" != "master" ]]; then
            echo "This is not master branch, aborting..." > /dev/stderr;
            exit 0;
          fi
      install:
        - cd makestack.org
        - yarn
      script:
        - >
          openssl aes-256-cbc -K $encrypted_35e7b7f33db9_key -iv $encrypted_35e7b7f33db9_iv
          -in deploy-key.encrypted -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - yarn deploy

notifications:
  on_success: change
  on_failure: change
