os: linux
dist: trusty
sudo: false

matrix:
  include:
    - language: ruby
      env: TARGET=server
      services:
        - postgresql
        - redis-server
      cache:
        directories:
          - server/vendor/bundle
      install:
        - cd server
        - bundle install --jobs 2 --path vendor/bundle
        - bundle exec rails db:migrate RAILS_ENV=test
      script: bundle exec rspec

    - language: node_js
      node_js: "8"
      env: TARGET=ui
      cache: yarn
      install:
        - cd server
        - yarn
      script: npm run build

    - language: c
      env: TARGET=linux
      sudo: true # because of mknod and docker
      addons:
        apt:
          packages:
            - build-essential
            - wget
            - qemu
            - zsh
      cache:
        apt: true
        directories:
          - linux/downloads
      script:
        - cd linux
        - ./build.sh
        - ./test.sh

notifications:
  on_success: change
  on_failure: change