notifications:
  email:
    on_success: changed
    on_failure: never

sudo: required
language: cpp

env:
  matrix:
    - TARGET=device/pci
    - TARGET=device/rtc
    - TARGET=device/virtio
    - TARGET=exec/elf
    - TARGET=fs/fat
    - TARGET=interfaces/channel
    - TARGET=interfaces/datetime
    - TARGET=interfaces/datetime_device
    - TARGET=interfaces/exec
    - TARGET=interfaces/fs
    - TARGET=interfaces/hal
    - TARGET=interfaces/io
    - TARGET=interfaces/lang
    - TARGET=interfaces/memory
    - TARGET=interfaces/net_device
    - TARGET=interfaces/pager
    - TARGET=interfaces/storage_device
    - TARGET=interfaces/thread
    - TARGET=interfaces/zeroed_pager
    - TARGET=kernel
    - TARGET=lang/cpp
    - TARGET=libs/libpci
    - TARGET=misc/genstartcpp
    - TARGET=tcpip
    - TARGET=SDK

# TODO
#    - TARGET=hal/arm
#    - TARGET=hal/lib
#    - TARGET=hal/posix_host
#    - TARGET=hal/x86

services:
  - docker

before_instrall:
  - docker pull ubuntu:16.04

install:
  - docker build -t ci-image -f .travis.dockerfile .

script:
  - docker run -e TARGET -e GH_TOKEN ci-image
