notifications:
  email:
    on_success: changed
    on_failure: never

sudo: required
language: cpp

env:
  matrix:
    - TARGET=kernel
    - TARGET=tcpip
    - TARGET=fs/fat
    - TARGET=exec/elf
    - TARGET=lang/cpp
    - TARGET=interfaces/channel
    - TARGET=interfaces/datetime
    - TARGET=interfaces/exec
    - TARGET=interfaces/fs
    - TARGET=interfaces/hal
    - TARGET=interfaces/io
    - TARGET=interfaces/lang
    - TARGET=interfaces/memory
    - TARGET=interfaces/pager
    - TARGET=interfaces/thread
    - TARGET=interfaces/storage_device
    - TARGET=interfaces/net_device
    - TARGET=interfaces/datetime_device
    - TARGET=resea.net
    - TARGET=SDK

services:
  - docker

before_instrall:
  - docker pull ubuntu:16.04

install:
  - docker build -t ci-image -f .travis.dockerfile .

script:
  - docker run -e TARGET -e GH_TOKEN ci-image
