language: ruby
rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0

cache:
  directories:
    - vendor/bundle

install:
  - cp config/database.yml.example config/database.yml
  - bundle install --jobs 4 --path vendor/bundle
  - bundle exec rake db:migrate
  - bundle exec rake user:add name=guest password=123

script:
  - ./.travis.sh
