language: ruby
services:
  - postgresql
  - mysql

rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0

cache:
  directories:
    - vendor/bundle

env:
  - DB=sqlite
  - DB=postgres
  - DB=mysql

install:
  - bundle install --jobs 4 --path vendor/bundle
  - mysql -e 'create database busybook'
  - psql -c 'create database busybook' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake user:add username=guest password=123

script:
  - ./.travis.sh
