name: arm
category: library
license: Public Domain
summary: The HAL library for ARM processors
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
requires: [cpp, genstartc]

# Interfaces which this package uses
uses: []

# Interfaces which this package implements
implements: [hal]

#
#  Type definitions
#
type:

#
#  Interface definitions
#
interface:

#
#  Machines
#
includes:
  - machines/raspi/config.yml
  - machines/versatileab/config.yml

#
#  Config
#
global_config:
  HAL_GENSTART:
    default: ./packages/genstartc/genstartc

config:
  SOURCES:
    set:
      - src/startup.c
      - src/debug.c
      - src/thread.c
      - src/memory.c
      - src/hw.c
      - src/vm.c
      - src/cpu.c
      - src/init.S
      - src/callback.c
