name: arm
category: library
license: Public Domain
summary: The HAL library for ARM processors
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
requires: [cpp]

# Interfaces which this package uses
uses: []

# Interfaces which this package implements
implements: [hal]

#
#  Type definitions
#
type:

#
#  Interface definitions
#
interface:

#
#  Config
#
global_config:
  HAL_LINK:
    default: >
      $(LD) -Map $(BUILD_DIR)/executable.map
      -nostdlib -nodefaultlibs
      -Tpackages/arm/src/executable.ld
      $(LIBGCC)
      -o
  HAL_RUN:
    default: packages/arm/run
  HAL_GENSTART:
    default: ./packages/posix_host/genstart
  CFLAGS:
   append_words: >
     -ffreestanding
     -mcpu=arm1176jzf-s -mfloat-abi=soft
     -Ipackages/arm/src 

config:
  SOURCES:
    set:
      - src/startup.c
      - src/debug.c
      - src/thread.c
      - src/memory.c
      - src/hw.c
      - src/vm.c
      - src/cpu.c
      - src/io.c
      - src/init.S
      - src/callback.c
