name: tcpip
category: application
id: 9
license: Public Domain
summary: The TCP/IP server
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Prefered language
lang: c

# Required packages
requires: [cpp]

# Interfaces which this package uses
uses: []

# Interfaces which this package implements
implements: []


#
#  Type definitions
#
types:


#
#  Interface definitions
#
interface:

#
#  Config
#
config:
  SOURCES:
    set:
      - src/api.c
      - src/arp.c
      - src/endian.c
      - src/icmp.c 
      - src/instance.c 
      - src/ip.c 
      - src/ipv4.c
      - src/malloc.c
      - src/mbuf.c
      - src/receive.c
      - src/udp.c
      - src/session.c
      - src/startup.c
