name: thread
category: interface
id: 6
license: Public Domain
summary: The threading server
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
requires: []
lib_requires: []

# interfaces which this package uses
uses: []

# interfaces which this package implements
implements: []


#
#  Type definitions
#
type:

#
#  interface definitions
#
interface:
  create:
    id: 1
    payloads:
      - name: group
        type: id
      - name: name
        type: Array<uchar>
        attrs: [readonly]
  create_reply:
    id: 2
    payloads:
      - name: result
        type: result
      - name: thread
        type: id
      - name: group
        type: id

  delete:
    id: 3
    payloads:
      - name: thread
        type: id
  delete_reply:
    id: 4
    payloads:
      - name: result
        type: result

  start:
    id: 5
    payloads:
      - name: thread
        type: id
  start_reply:
    id: 6
    payloads:
      - name: result
        type: result

  block:
    id: 7
    payloads:
      - name: thread
        type: id

  unblock:
    id: 8
    payloads:
      - name: thread
        type: id

  set:
    id: 9
    payloads:
      - name: thread
        type: id
      - name: entry
        type: addr
      - name: arg
        type: addr
      - name: stack
        type: addr
      - name: stack_size
        type: size
  set_reply:
    id: 10
    payloads:
      - name: result
        type: result

  get_current_thread:
    id: 11
    payloads:

  get_current_thread_reply:
    id: 12
    payloads:
      - name: thread
        type: id
      - name: group
        type: id

# TODO:
#
#  .wait(addr, val)
#  .wake(addr, wake_num_max)
#
