name: x86
category: library
license: Public Domain
summary: The HAL library for x86
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
depends: [cpp, genstartc]
lang: c

# OS requirements
os_requirements:
  osx:
    homebrew:
      packages:
        - qemu
        - xorriso
        - "./packages/x86/osx/grub.rb --HEAD"

# Interfaces which this package uses
uses: [posix_host] # we use genstart in posix_host

# Interfaces which this package implements
implements: [hal]


#
#  Type definitions
#
type:

#
#  Interface definitions
#
interface:

#
#  Config
#
global_config:
  HAL_LINK:
    default: $(LD) -Map $(BUILD_DIR)/executable.map -nostdlib -nodefaultlibs -Tpackages/x86/src/executable.lds -o
  HAL_RUN:
    default: packages/x86/run
  HAL_GENSTART:
    default: ./packages/genstartc/genstartc
  HAL_GENIMAGE:
    default: ./packages/x86/genimage
  CFLAGS:
    append_words: >
      -m64 -ffreestanding -mno-sse -mno-mmx
      -fno-stack-protector -mno-red-zone
      -mcmodel=large 
      -Ipackages/x86/src
  CXXFLAGS:
    append_words: >
      -m64 -ffreestanding -mno-sse -mno-mmx
      -fno-stack-protector -mno-red-zone
      -mcmodel=large 
      -Ipackages/x86/src
  QEMU:
    default: qemu-system-x86_64

config:
  SOURCES:
    set:
      - src/startup.cpp
      - src/asm.S
      - src/exception.cpp
      - src/gdt.cpp
      - src/global.cpp
      - src/handler.cpp
      - src/idt.cpp
      - src/init.S
      - src/init2.cpp
      - src/interrupt.cpp
      - src/interrupt_handler.S
      - src/ioapic.cpp
      - src/localapic.cpp
      - src/pic.cpp
      - src/print.cpp
      - src/smp.cpp
      - src/startup.cpp
      - src/thread.cpp
      - src/tss.cpp
      - src/vm.cpp
      - src/cpu.cpp
      - src/handler.cpp
      - src/callback.cpp

