os_releases: &os_releases

defaults: &defaults
  <<: *os_releases

development:
  os_releases:
    a:
      linux:
        x86_64:
          url: http://localhost:10101/os/x86_64.img
        raspberrypi3:
          url: http://localhost:10101/os/raspberrypi3.img
        mock:
          url: http://localhost:10101/os/mock.img
    b:
      linux:
        x86_64:
          url: http://localhost:10101/os/x86_64.img
        raspberrypi3:
          url: http://localhost:10101/os/raspberrypi3.img
        mock:
          url: http://localhost:10101/os/mock.img

test:
  os_releases:
    a:
      linux:
        x86_64:
          url: http://localhost:10101/os/x86_64.img
        raspberrypi3:
          url: http://localhost:10101/os/raspberrypi3.img
        mock:
          url: http://localhost:10101/os/mock.img

production:
  <<: *defaults
