os_releases: &os_releases

defaults: &defaults
  <<: *os_releases

development:
  outgoing_webhook_limit_per_hour: 5000
  push_to_sakuraio_limit_per_hour: 5000
  os_releases:
    a:
      title: 'MakeStack Linux version a'
      linux:
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img
    b:
      title: 'MakeStack Linux version b'
      linux:
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img

test:
  outgoing_webhook_limit_per_hour: 3600
  push_to_sakuraio_limit_per_hour: 5000
  os_releases:
    z:
      linux:
        title: 'MakeStack Linux version z'
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img
    v123.456.789:
      linux:
        title: 'MakeStack Linux version v123.456.789'
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img
    a:
      linux:
        title: 'MakeStack Linux version a'
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img

production:
  <<: *defaults
