os_releases: &os_releases

defaults: &defaults
  <<: *os_releases

development:
  outgoing_webhook_limit_per_hour: 5000
  os_releases:
    a:
      linux:
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img
    b:
      linux:
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img

test:
  outgoing_webhook_limit_per_hour: 3600
  os_releases:
    a:
      linux:
        x86_64:
          url: http://localhost:8100/repos/os/x86_64.img
        raspberrypi3:
          url: http://localhost:8100/repos/os/raspberrypi3.img
        mock:
          url: http://localhost:8100/repos/os/mock.img

production:
  <<: *defaults
