a:
  linux:
    title: 'MakeStack Linux version a'
    assets:
      x86_64:
        url: http://localhost:8100/repos/os/x86_64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      mock:
        url: http://localhost:8100/repos/os/mock.img
        shasum: 733045e06887bba40eadfc4ee9012b588c58c5762d6a7e5780ac74ff4ea24ebb
b:
  linux:
    title: 'MakeStack Linux version b'
    assets:
      x86_64:
        url: http://localhost:8100/repos/os/x86_64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      mock:
        url: http://localhost:8100/repos/os/mock.img
        shasum: 733045e06887bba40eadfc4ee9012b588c58c5762d6a7e5780ac74ff4ea24ebb
c:
  linux:
    title: 'MakeStack Linux version c'
    assets:
      x86_64:
        url: http://localhost:8100/repos/os/x86_64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      mock:
        url: http://localhost:8100/repos/os/mock2.img
        shasum: 733045e06887bba40eadfc4ee9012b588c58c5762d6a7e5780ac74ff4ea24ebb
