a:
  linux:
    title: 'MakeStack Linux version a'
    assets:
      x86_64:
        url: http://localhost:8100/repos/os/x86_64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      mock:
        url: http://localhost:8100/repos/os/mock.img
b:
  linux:
    title: 'MakeStack Linux version b'
    assets:
      x86_64:
        url: http://localhost:8100/repos/os/x86_64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      mock:
        url: http://localhost:8100/repos/os/mock.img
c:
  linux:
    title: 'MakeStack Linux version c'
    assets:
      x86_64:
        url: http://localhost:8100/repos/os/x86_64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      mock:
        url: http://localhost:8100/repos/os/mock2.img
