a:
  linux:
    title: 'MakeStack Linux version a'
    assets:
      x64:
        url: http://localhost:8100/repos/os/x64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      sdk:
        url: http://localhost:8100/repos/os/sdk.img
        shasum: 733045e06887bba40eadfc4ee9012b588c58c5762d6a7e5780ac74ff4ea24ebb
b:
  linux:
    title: 'MakeStack Linux version b'
    assets:
      x64:
        url: http://localhost:8100/repos/os/x64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      sdk:
        url: http://localhost:8100/repos/os/sdk.img
        shasum: 733045e06887bba40eadfc4ee9012b588c58c5762d6a7e5780ac74ff4ea24ebb
c:
  linux:
    title: 'MakeStack Linux version c'
    assets:
      x64:
        url: http://localhost:8100/repos/os/x64.img
      raspberrypi3:
        url: http://localhost:8100/repos/os/raspberrypi3.img
      sdk:
        url: http://localhost:8100/repos/os/sdk2.img
        shasum: 733045e06887bba40eadfc4ee9012b588c58c5762d6a7e5780ac74ff4ea24ebb
