include_if: "MACHINE == 'versatileab'"

global_config:
  CXXFLAGS:
    append_words: >
      -ffreestanding
      -I{{ ARM_DIR }}/src
      -I{{ ARM_DIR }}/machines/versatileab/include
      -mcpu=arm1176jzf-s -mfloat-abi=soft
  HAL_RUN:
    default: {{ ARM_DIR }}/machines/versatileab/run
  HAL_GENIMAGE:
    default: {{ ARM_DIR }}/machines/versatileab/genimage
  HAL_LINK:
    default: >
      $(LD) -Map $(BUILD_DIR)/executable.map
      -nostdlib -nodefaultlibs
      -T{{ ARM_DIR }}/machines/versatileab/executable.lds
      -o

config:
  LIBS:
    set:
      - '$(shell $(CC) -print-libgcc-file-name)' # XXX

