name: zeroed_pager
id: 1002
category: interface
license: Public Domain
summary: The interface of the zero-filled pager
description:

warning:     # some important things to note
info: 

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
depends: []
lib_depends: []

# interfaces which this package uses
uses: []

# interfaces which this package implements
implements: []


#
#  Type definitions
#
types:

#
#  interface definitions
#
interface:
