name: lang
category: interface
license: Public Domain
summary: The interface of language libraries
description:
author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net
warning:
info: 

# Required packages
depends: []

# interfaces which this package uses
uses: []

# interfaces which this package implements
implements: []

#
#  Type definitions
#
types:

#
#  interface definitions
#
interface:
