sqlite: &sqlite
  adapter: sqlite3
  database: db/test.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  encoding: utf8mb4
  collation: utf8mb4_bin

postgresql: &postgresql
  adapter: postgresql
  username: postgres

test:
  pool: 5
  timeout: 5000
  host: localhost
  password:
  database: busybook_test
  <<: *<%= ENV['DB'] %>
