name: io
category: interface
id: 5
license: Public Domain
summary:     # brief explanation
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net

# Required packages
requires: []
lib_requires: []

# Interfaces which this package uses
uses: []

# Interfaces which this package implements
implements: []

#
#  Type definitions
#
type:
  IOSpace:
    type: const
    size: UInt8
    consts:
      IOSPACE_PORT: 1
      IOSPACE_MEM:  2

#
#  Interface definitions
#
interface:
  allocate:
    id: 1
    payloads:
      - name: iospace
        type: io(IOSpace)
      - name: addr
        type: Addr
      - name: size
        type: Size
  allocate_reply:
    id: 2
    payloads:
      - name: result
        type: Result
      - name: addr
        type: Addr

  release:
    id: 3
    payloads:
      - name: iospace
        type: io(IOSpace)
      - name: addr
        type: Addr
