title: MakeStack Documentation
email: nuta@seiya

description:
baseurl: ""
url:
permalink: /documentation
github_username:  makestack

collections:
  - guides

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: documentation

destination: ../server/public/documentation
exclude:

markdown: kramdown
plugins:
highlighter: rouge

sass:
    sass_dir: _sass

