name: cpp
category: library
license: Public Domain
summary: The language library for C++
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net   # e.g. http://example.com/foo/bar

# Required packages
requires: []

# Interfaces which this package uses
uses: []

# Interfaces which this package implements
implements: [lang]

global_config:
  LANG:
    append:
      c:
        ext:  c
        abbrev: CC
        stub:
          prefix: resea/
          suffix: .h
        compile: '$(CC) $(CFLAGS) -DPACKAGE_NAME=\"${PACKAGE_NAME}\" -c -o'
        mkdeps:  ./packages/cpp/mkdeps
        scaffold: ./packages/cpp/scaffold
        genstub: ./packages/cpp/genstub
      asm:
        ext:  S
        abbrev: AS
        mkdeps: touch
        compile: "$(CC) $(CFLAGS) -c -o"
      cpp:
        ext:  cpp
        abbrev: CXX
        stub:
          prefix: resea/
          suffix: .hpp
        compile: echo
        mkdeps: touch
        scaffold: ./packages/cpp/scaffold
        genstub: ./packages/cpp/genstub
  CFLAGS:
    default: >
      -Wall -ggdb3 -std=c99 -Wno-incompatible-library-redeclaration
      -fdiagnostics-color     
      -Ipackages/cpp/src -I$(BUILD_DIR)/stubs/c


config:
  - SOURCES:
      set:
        - src/ctype.c
        - src/hal_callback.c
        - src/channel.c
        - src/string.c
        - src/syscall.c
        - src/memory.c
        - src/mutex.c
        - src/printfmt.c
        - src/io.c
  - if: "HAL == 'x86'"
    SOURCES:
      set:
        - src/x86.c
  - if: "HAL == 'posix_host'"
    SOURCES:
      set:
        - src/posix_host.c

#
#  Type definitions
#
type:

#
#  Interface definitions
#
interface:
