name: cpp
category: library
license: Public Domain
summary: The language library for C++
description: # longer explanation

warning:     # some important things to note
info:        # what we should know

author: Seiya Nuta
email: nuta@seiya.me
homepage: http://resea.net   # e.g. http://example.com/foo/bar

# Required packages
depends: []

lang: cpp

# OS requirements
os_requirements:
  osx:
    homebrew:
      packages:
        - "./osx/clang-static-analyzer.rb"
        - "./osx/x86_64-elf-gcc.rb"
        - "./osx/x86_64-elf-binutils.rb"
        - "./osx/arm-elf-eabi-gcc.rb"
        - "./osx/arm-elf-eabi-binutils.rb"
        - lcov
  ubuntu:
    apt:
      packages:
        - clang
        - gcc
        - lcov

# Interfaces which this package uses
uses: [memory, io]

# Interfaces which this package implements
implements: [lang]

global_config:
  LANG:
    append:
      c:
        ext:  c
        abbrev: CC
        stub:
          prefix: resea/
          suffix: .h
        compile: '${CC} ${CFLAGS} -DPACKAGE_NAME=\"${PACKAGE_NAME}\" -c -o'
        mkdeps:   ./${CPP_DIR}/mkdeps "${CXX} ${CXXFLAGS}"
        scaffold: ./${CPP_DIR}/scaffold
        genstub:  ./${CPP_DIR}/genstub
        doctor:   ./${CPP_DIR}/doctor
      asm:
        ext:  S
        abbrev: AS
        mkdeps: touch
        compile: "${CC} ${CFLAGS} -c -o"
      cpp:
        ext:  cpp
        abbrev: CXX
        stub:
          prefix: resea/
          suffix: .h
        compile: '${CXX} ${CXXFLAGS} -DPACKAGE_NAME=\"${PACKAGE_NAME}\" -c -o'
        mkdeps:   ./${CPP_DIR}/mkdeps "${CXX} ${CXXFLAGS}"
        scaffold: ./${CPP_DIR}/scaffold
        genstub:  ./${CPP_DIR}/genstub
        doctor:   ./${CPP_DIR}/doctor
  CFLAGS:
    append_words: >
      -Wall -ggdb3 -std=c99 -Wno-incompatible-library-redeclaration
      -fdiagnostics-color
      -I${CPP_DIR}/src -I${BUILD_DIR}/stubs/c
  CXXFLAGS:
    append_words: >
      -Wall -ggdb3 -std=c++14 -Wno-incompatible-library-redeclaration
      -fdiagnostics-color -fno-exceptions
      -I${CPP_DIR}/src -I${BUILD_DIR}/stubs/cpp


config:
  - SOURCES:
      set:
        - src/ctype.cpp
        - src/hal_callback.cpp
        - src/channel.cpp
        - src/string.cpp
        - src/syscall.cpp
        - src/memory.cpp
        - src/mutex.cpp
        - src/printfmt.cpp
        - src/io.cpp
  - if: "ENV == 'test'"
    SOURCES:
      set:
        - tests/test.cpp
  - if: "HAL == 'x86'"
    SOURCES:
      set:
        - src/x86.cpp
  - if: "HAL == 'posix_host'"
    SOURCES:
      set:
        - src/posix_host.cpp

#
#  Type definitions
#
type:

#
#  Interface definitions
#
interface:
